version: "3.9"

services:
  cron:
    build: .
    container_name: cron
    network_mode: "none"
    restart: unless-stopped
    init: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cron-bashhistory:/commandhistory

    env_file:
      - .env

volumes:
  cron-bashhistory: # нужен только для отладки
